language: ruby
rvm:
- 2.3
before_install:
- gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
- gem install bundler -v '< 2'
install: bundle install
script:
- gem build facebookbusiness.gemspec
deploy:
  provider: releases
  api_key:
    secure: 1RAZgbgy1uPpWlnYv2WPUZ8w0Q7RwKTgCbmbXE+x+4bmjpCZvIJC6ciEcl8Iyw3P1qqEAuEFSbmpDoAfj1nwVJVBhw4BL0MQqN84Xsan3qhXjbHTnIokyDjM1/17Mw/7QsXvGpFEjEqoLIeGkxZbYIealf3L1I00zR+OH9oy+z8SZ3y572TQhTW7NrbuwwsNT33/EJIk8qW2UjdsJB7r+4A4JopakYZEd0yN5PsndJeo/8lYJzSqYRkUFUGdpmp0oG2yzy3j1i4Y81rH0ZJMuYRqoKlqyFmkAhBHICWUkwdu/F2WaF06QYUor47K9engUviXzhefYbXYYIhrY5sn68PZqo0ZnPBu1IP/+Ezt6IrFUTiHCF5MPUJbmpfrwFf3kXFBygixaVqaCzHjJFOI0j95z2/y2es3xO0dh030SKfFCYM+EZmafQ0EUEx8vfo7mS8AH6vEoFkv5Ohz/s8Vrn77AhT/B6xy6KFJ1OIAXe1NdK4k7kTjvO2iXO2hjPlxQdYuR0HBo8CEvlfEuBh89zcm0o0nVV7eseTeyBu7NoXeVecc9Z+IENB2gvlkEKkNNkZqNCCreAWjfy+M2GuOeDrMtnmFeYk1F9vnHFeQmMTneRMKwKpaOwpxttr3vFjua3c3jj1N4YY+KtuYPin7gNQEmk7IIaqKL1F2ClttWJ8=
  file: "./"
  on:
    repo: facebook/facebook-ruby-business-sdk
    branch: add-tag
