language: ruby
rvm:
- 2.3
branches:
  only:
  - master
before_install:
- gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
- gem install bundler -v '< 2'
install: bundle install
script:
- gem build facebookbusiness.gemspec

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name ${GH_NAME}
  - git config --local user.email ${GH_EMAIL}
  - export TRAVIS_TAG=$(sed -n "s/.* VERSION = '\(.*\)\'/\1/p" lib/facebook_ads/version.rb)
  - echo $TRAVIS_TAG
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  skip_cleanup: true

env:
  global:
  - secure: y5V2iYaddGSeI6kpPIQnokTuNT07oQZaONbb/Sgxu+sIVZ9OeRpko3bt4ItAzKxPOMCE7edeJZHCqF9sj1NvZo+oU5A/nnH7MkjIXwI7Lyf/pGtD6nzsFoNyEV3LHHe9gbzSjJWUix3e3EqicwwJGqIzW5EA4VaWx6Cd4uoK6uTo4Rzyh2cMtD4WYRtdytEdkY25XuAAx0G5i1rGNZseGGeM5us0DIq+AWMakmYWrUO/EHEOcv7vQhJkoOLcNAToqkOJVhVSOZ6oEEN+A99Rz3j54Pq5nzr1TMgeDrYBF7xYoT4lRTddbE5kuFjcz7SN3FwWfc4D37594phfaiWRNrJ32spZWqOR4FhrHdymc6ftGBfx5OTPYrfYT6GLoWLeEzQFp0/ZqoKWqz4JUU4HmvXu3nDQePw2cflg9QoU3gr77uNn0cAWRmYYULmK9WA7Qrj2i322jcfjChV3As9yiSbt1U6Rpsw+P5u4j9hfrjx2whsCblAvu6D+fQky0qG+csUW4o/y4QznN8g626fCObfO8YXwEjFj4p0r2u7Suej2YK4X4wa7wzSa1G3DOFFBt8tgBabnNCx45GYmpmfichCBbTNY3J5uGBjnyYxKQI+dZveJjB8dvb7uSjx9KflKQ4u3XFnRPRvWa3mFxHy1laN4JXpZeV2IzvyIl2J7f+Y=
  - secure: eZ5qpGErwN/csQtr/MlF/zFBpiz4NqX5B45R3rkoUc4mR8p4JoE0RelKWERJ1ZLhHbZO6A7qefZ6Rdmizw/w5SCYs69JzAUUXfS/+cBRmUmFV1qV4qEmRPUVKSUarOIxopCMsAvOpDFEc2sRwzZybY8mvWhwV3RIMA7qKpvisOZu/xAi94lGwFRbVHXTf9WUh7RreQsg0Tmml7A6auR/1xHK9f6Yti1Y+HuvvfeUuxsVLGprrmULF9ecIUvjKGG2GTVxzXn3iFkgtZMprYovq6hbn7JRt5vzw+QqPd6dnmsA96On9JE3sUtTt8Vp+nD0eCJZ5vws95dC7PNPyUkV77o53wd9tT//RrwyILMlGZE/TweQRvqgQSpA4mXSbN3VQvQLHT8Jt+yOhDGzAqR7GI6x/qzpm9qo2X1BemI6OGuRMdJXAsNuw5y4LfSW0LvdvzUjj5or0f5F/w60MZuy6JvnGflVcLFdgvgQMB4Fs4b8YemNGx0yG/VWm5Em6UEllDcRJsXUrf6sJb7GBWXRPGVDZUuE+Yn1uRFzDB8MypqtpdwjFnuObHqv7JnxHZPyjVmcrupnyrJ5l66qUnrRDU4hUyr1upmHSrOeEuhwhKMajxExjwd/TD6MqSjwIus+rfVLhS6d0E6MpTKIN4TF4+irGRuWSPcTgFvxK1E3JSM=
  - secure: P0rLLDOE4xZrfBSzMbhhqwIz7eAZyQUUFWxPQM2mEeR5ZDJ4Yi8zi6I8ZojkfeBAbsSe6lNL5CHWYN//zPtU8xM7Ik7Xn8BMY8xZzZgstFVJmty5aM+IxLLtEAV3TQQtn/IyV7rGtwcl7UbuuJE1R0oLtAfoBGcALcWxc4laxXGUsp+C3kFUcJQBO2Snj2RuKdzDQ2RzEsIbzuVHcAcYbOMfbC+2HBMAf+91ND/niwxGckwj+ym7kcETkmmIq6TtUjfVsL6TbuzHOnEMqdtUkYIi1lYCWgGg08X+Qchab1/PdjGj8FqRr/F9UfOFIIR/el2i21guQYqMq0jQ4cKYq5wYcQi6UQfWOET0WAAfWFAzkhQF/kll2al4ZHSvEaIy1lsaRApVeOp9jE/D9LCZATYPuB/0GiY2BJuU9dq+rWNBrLxV/pxoYBVOeYBmXqeTRuMGIjGScvjXL1OrJ5pDYmWGK1eblVNX4Fx28iGaJTJu1Cc2B+4IV+hifYpMm9NpKGuJWiqrFQNXFnszrx77dRWrAmyoIF0pSFJ/G7bYuu3D/tx1ww6VlTxPqSoUKvmzs46tE6qHOrKk+/GOVHXwbDXko3OTa5mgZp+cRU5X9PtMELB29gx+wtuoYIH7C71t6Cifw5G2gPDEHSxag1dhDYTQaTqXG98FSuLGRtNIx6U=
  - secure: m9RGq0RwA07zvfmECxivSGhHcWBIYWbkI+GEpwdFpUM6jhnTTMEBMCE+lQ6iMeOfC3Q6XgDHjIEPL0L6lr/qgQXBIOYRtdgmPQncZnWAtYfSmticzeqm15vi2DwH87KjyXpAxaUbcpn/QTWYK5yeXmGL20CfGmmRROIkLOQOlQl3tgQAeiJpI93YqKXFeg4cabKp9LEa5lhy5LH/ysM4Io4jkl+v2JWFNd4VG6rFOalFJoUMpHZLG/evTnWDR9S/jaGV+yjdMOqbGb9VTZRpm2lExzjZkCTc18kzz9CPQ7rbIZWmxjXRWhShyh2sOMZGYmfZK/emsBuScZr9i1LpzVKfSZzOvYIizSsdv/kmLlyM+vyH3q3/iIIhUIA22/cmVjNUym9d0apt/9mBrTde5RLfJHbiBmaavaGQMNz1fawr0aLkdVo/YBGbRn3mJOo3JCFn/TTl2rT5sWqXC7bJh1cW+LVnTCtSmYoZo+PNbNEnwRk4ZONlw+7iWhBEFBr4cU0egecKNPhVMj1ohvqsn6WfQGNhGQIOmmzZVhdCXWQKQag0KiP9WGAW1qAxu3JukTOpqxnrWktEmXRR+blmGjVsvlGfyDJMe8qiullaeyQqm/pNGxjh++Mpg0LuMNqJ9FGM6h/p0OFwO7Lxk7iwsUQ/jVCjnCoiSGaFDzqklhY=
