language: ruby
rvm:
- 2.3
before_install:
- gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
- gem install bundler -v '< 2'
install: bundle install
script:
- gem build facebookbusiness.gemspec
deploy:
  provider: releases
  api_key:
    secure: 3lKeHHmg/0RAskePFK30573YI9NkujaDe11rnY5G94dL1U2rJHzgOulCP43lbp+rqMYQBQm3XjdZEXhbW3mHrE+WYRUeR604vA59huXGdDakVmn6VFyJ0duUqSC4Hzp/d1BrIhaLq8qFrqyeE4gxaSgDK1Th/mKyp5fqVFV4QEXEyZwhQaY7/7LxxjIxGkX0JQNfxPYPm/Ic2yGe31KvfVKJsAnbwST0Gr7tECpS0QH6HiQC2wklAGYQ2BfrakPyBKnmMlgePvMHSN/g9cqMD+u2xzA4busA3s7hRhcbxx+Ik/3cmzw+38x/rzasgV3YGDUPDQod4VHdggSfMQ0Oth1yvZUqo+8+n/+1nnXrTQDJ+ntYcZ5dkPWhBQR45OAjpolOgv5y0UgvB2JFMDZ0sviX/OBHwdcIiy8E1uhYwtNz3C/zTKJVB9WQPwI1F2A1zTRxMr/N2SoapIxEnw+0b5OX9hDFfKQaWMkZbGobWueYa2wWyuvugQYZfVDMtqaxv/4qPn2iYyjnXJrjmRm/SCU9ySbrdsxGYbRX64n4ENeJoXeNphFonVrC3MnyH7MUX0UwwaBJJ44K5dNGuSDCJF6d232Uk6p8heU2bv154fntJJZMPsVUZsVIU7zhm8jtc1rrItyHRxcESXbGb06St22/a5WhHJeH4AVx0QaFSH0=
  file: "./"
  on:
    repo: facebook/facebook-ruby-business-sdk
    branch: add-tag
