language: ruby
rvm:
- 2.3
branches:
  only:
  - master
before_install:
- gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
- gem install bundler -v '< 2'
install: bundle install
script:
- gem build facebookbusiness.gemspec
- "./.travis/tag_version.sh"
env:
  global:
    #GH_TOKEN
    secure: y5V2iYaddGSeI6kpPIQnokTuNT07oQZaONbb/Sgxu+sIVZ9OeRpko3bt4ItAzKxPOMCE7edeJZHCqF9sj1NvZo+oU5A/nnH7MkjIXwI7Lyf/pGtD6nzsFoNyEV3LHHe9gbzSjJWUix3e3EqicwwJGqIzW5EA4VaWx6Cd4uoK6uTo4Rzyh2cMtD4WYRtdytEdkY25XuAAx0G5i1rGNZseGGeM5us0DIq+AWMakmYWrUO/EHEOcv7vQhJkoOLcNAToqkOJVhVSOZ6oEEN+A99Rz3j54Pq5nzr1TMgeDrYBF7xYoT4lRTddbE5kuFjcz7SN3FwWfc4D37594phfaiWRNrJ32spZWqOR4FhrHdymc6ftGBfx5OTPYrfYT6GLoWLeEzQFp0/ZqoKWqz4JUU4HmvXu3nDQePw2cflg9QoU3gr77uNn0cAWRmYYULmK9WA7Qrj2i322jcfjChV3As9yiSbt1U6Rpsw+P5u4j9hfrjx2whsCblAvu6D+fQky0qG+csUW4o/y4QznN8g626fCObfO8YXwEjFj4p0r2u7Suej2YK4X4wa7wzSa1G3DOFFBt8tgBabnNCx45GYmpmfichCBbTNY3J5uGBjnyYxKQI+dZveJjB8dvb7uSjx9KflKQ4u3XFnRPRvWa3mFxHy1laN4JXpZeV2IzvyIl2J7f+Y=
