name: Ruby Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        version: [2.5, 2.6, 2.7]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
            
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version }}
      
      - name: Before install
        run: gem install bundler -v "< 2.0"

      - name: Bundle install
        run: bundle install
      
      - name: exec rake
        run: bundle exec rake

      - name: Gem build
        run: gem build *.gemspec
